pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                dir('examble/simple-node-js-react-npm-app'){
                    sh '''
                    npm config set proxy http://192.168.101.137:8080
                    npm config set https-proxy http://192.168.101.137:8080
                    npm config set registry http://registry.npmjs.org
                    '''
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('examble/simple-node-js-react-npm-app'){
                    sh './jenkins/scripts/test.sh'
                }
            }
        }
        stage('Deliver') {
            steps {
                dir('examble/simple-node-js-react-npm-app'){
                    sh './jenkins/scripts/deliver.sh'
                    sh './jenkins/scripts/kill.sh'
                }
            }
        }
    }
}
